package com.hins.boot.entity;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.SId
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Sname
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    private String sname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Sage
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    private Date sage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Ssex
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    private String ssex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.SId
     *
     * @return the value of Student.SId
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.SId
     *
     * @param sid the value for Student.SId
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public void setSid(String sid) {
        this.sid = sid == null ? null : sid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Sname
     *
     * @return the value of Student.Sname
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Sname
     *
     * @param sname the value for Student.Sname
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Sage
     *
     * @return the value of Student.Sage
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public Date getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Sage
     *
     * @param sage the value for Student.Sage
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public void setSage(Date sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Ssex
     *
     * @return the value of Student.Ssex
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public String getSsex() {
        return ssex;
    }

    @Override
    public String toString() {
        return "Student{" +
                "sid='" + sid + '\'' +
                ", sname='" + sname + '\'' +
                ", sage=" + sage +
                ", ssex='" + ssex + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Ssex
     *
     * @param ssex the value for Student.Ssex
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }
}