package com.hins.boot.entity;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.TId
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.Tname
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    private String tname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.TId
     *
     * @return the value of Teacher.TId
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.TId
     *
     * @param tid the value for Teacher.TId
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public void setTid(String tid) {
        this.tid = tid == null ? null : tid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.Tname
     *
     * @return the value of Teacher.Tname
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.Tname
     *
     * @param tname the value for Teacher.Tname
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }
}