package com.hins.boot.dao;

import com.hins.boot.entity.Course;

public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    int insertSelective(Course record);
}