package com.hins.boot.dao;

import com.hins.boot.entity.SC;

public interface SCMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SC
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    int insert(SC record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SC
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    int insertSelective(SC record);
}