package com.hins.boot.dao;

import com.hins.boot.entity.Student;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    int insertSelective(Student record);
    //查询所有
  List<Student> listStudent();
}