package com.hins.boot.dao;

import com.hins.boot.entity.Teacher;
import org.apache.ibatis.annotations.Mapper;


public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Teacher
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Teacher
     *
     * @mbg.generated Thu Oct 22 13:57:23 CST 2020
     */
    int insertSelective(Teacher record);
}